### ISSUE TITLE
Failed to activate the block-travel package

### ISSUE THREAD

**Issue by capir** [leejarvis/block-travel#15]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [block-travel](https://github.com/leejarvis/block-travel) package, v1.0.4

### Stack Trace

Failed to activate the block-travel package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (<anonymous>:38:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -2:03.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-spacegray-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-perl",
      "language-ruby-on-rails",
      "language-ruby",
      "language-toml",
      "language-c",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-make",
      "language-property-list",
      "language-python",
      "language-xml",
      "language-yaml",
      "welcome",
      "vim-mode"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "projectHome": "/Users/c/work",
    "themes": [
      "spacegray-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
block-travel, v1.0.4
editor-stats, v0.17.0
language-todo, v0.7.0
spacegray-dark-ui, v0.5.0
todo-show, v0.5.1

# Dev
No dev packages
```

**Comment by leejarvis** [comment]
Sorry, but unfortunately this package is no longer maintained. I'll updated the README accordingly.
